export const CHANGE_ICE = "CHANGE_ICE";
export const CHANGE_SUGAR = "CHANGE_SUGAR";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const CHANGE_INGREDIENTS = "CHANGE_INGREDIENTS";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CHANGE_QUANTITY_OF_ITEM = "CHANGE_QUANTITY_OF_ITEM";
